[package]
name = "rustify"
version = "0.1.0"
description = "Rustify — lecteur de musique local"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rusqlite = { version = "0.31", features = ["bundled"] }
lofty = "0.21"
kira = { version = "0.9", features = ["mp3", "flac", "ogg", "wav", "cpal"] }
cpal = "0.15"
walkdir = "2"
uuid = { version = "1", features = ["v4"] }
dirs = "5"
base64 = "0.22"
tauri-plugin-global-shortcut = "2"
tauri-plugin-autostart = "2"
anyhow = "1"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
